### PR TITLE
DM-27935: start the mock controller just before connecting to it, for robustness

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Review by mareuter — APPROVED** [review]
Looks good to me. Was just curious about why the Commader enum got ditched.

**Comment by r-owen** [comment]
That is an excellent question. I am pretty sure that Tekniker uses one enum for all identification of "who is who", so it was needless duplication. It might have been smarter to verify that. But the value for HHD agreed, which is a strong indicator. I'll ask about it and complain if they don't follow that rule in the new software.

In other words: I should never have created the new enum in the first place.

**Comment by r-owen** [comment]
I have asked Tekniker that question (and what the value for CSC will actually be -- I guessed) and will update the code as needed on a new ticket.

**Comment by r-owen** [comment]
Followup: yes the values for AskForCommand are the same as the source identifiers, so the Commander enum class was unnecessary duplication.

**Pull request merged**
