### PR TITLE
DM-36432: report updated connected event and new telemetryConnected event

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by r-owen** [comment]
The reason there are separate `connected` and `telemetryConnected` events is that they are written by two separate processes. Unfortunately, as long as we need a separate process to handle the telemetry, I see no practical way to combine them. (Though if the CSC could easily keep up with the telemetry then we'd probably only have one TCP/IP socket).

**Review by wvreeven — APPROVED** [review]
Looks good to me. It took me a while to find out (because of the way GitHub presents the changes) that the `evt_telemetryConnected` with `connected=False` also is sent when the client is stopped. Very nice!

**Review by wvreeven — COMMENTED** [review]
Please note that one test case fails in Jenkins. Please fix that before merging the code into develop.

**Comment by r-owen** [comment]
That failing test turned out to be reproducible (thank heavens): I modified the code in question to wait for a remote to start before waiting for the telemetry client to start (instead of waiting for both at the same time, which was fine when the telemetry client didn't time out). I was running tests locally with Kafka, which didn't show the problem (because remotes start so quickly).

I also found andI fixed a test incompatibility with ts_xml 12.

**Pull request merged**
